import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { CareerEnum } from 'src/common/enums/career';
import { AnyData } from 'src/common/types';

import { Career } from 'src/domain/careers/entities/career.entity';
import { Repository } from 'typeorm';

@Injectable()
export class CareersService {
  private readonly logger = new Logger(CareersService.name);

  constructor(
    @InjectRepository(Career)
    private readonly repository: Repository<Career>,
  ) {}

  //?-------------------------------------------------------------------------//
  //? READ
  //?-------------------------------------------------------------------------//

  async findAll(): Promise<AnyData> {
    const data = await this.repository.manager
      .getTreeRepository(Career)
      .findTrees();

    return { data };
  }

  async findBySlug(slug: string): Promise<AnyData> {
    const parent = await this.repository.findOneOrFail({
      where: {
        slug,
      },
    });
    const data = await this.repository.manager
      .getTreeRepository(Career)
      .findDescendantsTree(parent);
    return { data: data.children };
  }

  //?-------------------------------------------------------------------------//
  //? SEED
  //?-------------------------------------------------------------------------//

  async seedCareer(): Promise<void> {
    let district;

    const root = new Career();
    root.slug = 'root';
    await this.repository.manager.save(root);

    const korea = new Career();
    korea.slug = CareerEnum.KOREA;
    korea.depth = 1;
    korea.parent = root;
    await this.repository.manager.save(korea);

    const seoul = new Career();
    seoul.slug = CareerEnum.SEOUL;
    seoul.depth = 2;
    seoul.parent = korea;
    await this.repository.manager.save(seoul);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GANGNAM_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GANGDONG_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GANGBUK_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GANGSEO_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GWANAK_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GWANGJIN_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GURO_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_GEUMCHEON_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_NOWON_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_DOBONG_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_DONGDAEMUN_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_DONGJAK_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_MAPO_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_SEODAEMUN_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_SEOCHO_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_SEONGDONG_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_SEONGBUK_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_SONGPA_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_YANGCHEON_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_YEONGDEUNGPO_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_YONGSAN_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_EUNPYEONG_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_JONGNO_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_JUNG_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SEOUL_JUNGNANG_GU;
    district.depth = 3;
    district.parent = seoul;
    await this.repository.manager.save(district);

    const busan = new Career();
    busan.slug = CareerEnum.BUSAN;
    busan.depth = 2;
    busan.parent = korea;
    await this.repository.manager.save(busan);
    district = new Career();
    district.slug = CareerEnum.BUSAN_JUNG_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_SEO_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_DONG_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_YEONGDO_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_BUSANJIN_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_DONGNAE_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_NAM_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_BUK_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_HAEUNDAE_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_SAHA_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_GEUMJEONG_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_GANGSEO_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_YEONJE_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_SUYEONG_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_SASANG_GU;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.BUSAN_GIJANG_GUN;
    district.depth = 3;
    district.parent = busan;
    await this.repository.manager.save(district);

    const incheon = new Career();
    incheon.slug = CareerEnum.INCHEON;
    incheon.depth = 2;
    incheon.parent = korea;
    await this.repository.manager.save(incheon);
    district = new Career();
    district.slug = CareerEnum.INCHEON_DONG_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_SEO_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_NAMDONG_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_JUNG_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_YEONSU_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_BUPYEONG_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_MICHUHOL_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_GYEYANG_GU;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_GANGHWA_GUN;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.INCHEON_ONGJIN_GUN;
    district.depth = 3;
    district.parent = incheon;
    await this.repository.manager.save(district);

    const ulsan = new Career();
    ulsan.slug = CareerEnum.ULSAN;
    ulsan.depth = 2;
    ulsan.parent = korea;
    await this.repository.manager.save(ulsan);
    district = new Career();
    district.slug = CareerEnum.ULSAN_DONG_GU;
    district.depth = 3;
    district.parent = ulsan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.ULSAN_NAM_GU;
    district.depth = 3;
    district.parent = ulsan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.ULSAN_BUK_GU;
    district.depth = 3;
    district.parent = ulsan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.ULSAN_JUNG_GU;
    district.depth = 3;
    district.parent = ulsan;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.ULSAN_ULJU_GUN;
    district.depth = 3;
    district.parent = ulsan;
    await this.repository.manager.save(district);

    const daejeon = new Career();
    daejeon.slug = CareerEnum.DAEJEON;
    daejeon.depth = 2;
    daejeon.parent = korea;
    await this.repository.manager.save(daejeon);
    district = new Career();
    district.slug = CareerEnum.DAEJEON_DONG_GU;
    district.depth = 3;
    district.parent = daejeon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEJEON_SEO_GU;
    district.depth = 3;
    district.parent = daejeon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEJEON_JUNG_GU;
    district.depth = 3;
    district.parent = daejeon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEJEON_DAEDEOK_GU;
    district.depth = 3;
    district.parent = daejeon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEJEON_YUSEONG_GU;
    district.depth = 3;
    district.parent = daejeon;
    await this.repository.manager.save(district);

    const daegu = new Career();
    daegu.slug = CareerEnum.DAEGU;
    daegu.depth = 2;
    daegu.parent = korea;
    await this.repository.manager.save(daegu);
    district = new Career();
    district.slug = CareerEnum.DAEGU_DONG_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_SEO_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_NAM_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_BUK_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_JUNG_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_SUSEONG_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_DALSEO_GU;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.DAEGU_DALSEONG_GUN;
    district.depth = 3;
    district.parent = daegu;
    await this.repository.manager.save(district);

    const gwangju = new Career();
    gwangju.slug = CareerEnum.GWANGJU;
    gwangju.depth = 2;
    gwangju.parent = korea;
    await this.repository.manager.save(gwangju);
    district = new Career();
    district.slug = CareerEnum.GWANGJU_GWANGSAN_GU;
    district.depth = 3;
    district.parent = gwangju;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GWANGJU_DONG_GU;
    district.depth = 3;
    district.parent = gwangju;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GWANGJU_SEO_GU;
    district.depth = 3;
    district.parent = gwangju;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GWANGJU_NAM_GU;
    district.depth = 3;
    district.parent = gwangju;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GWANGJU_BUK_GU;
    district.depth = 3;
    district.parent = gwangju;
    await this.repository.manager.save(district);

    const sejong = new Career();
    sejong.slug = CareerEnum.SEJONG;
    sejong.depth = 2;
    sejong.parent = korea;
    await this.repository.manager.save(sejong);

    const gyeonggi = new Career();
    gyeonggi.slug = CareerEnum.GYEONGGI;
    gyeonggi.depth = 2;
    gyeonggi.parent = korea;
    await this.repository.manager.save(gyeonggi);

    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GAPYEONG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GOYANG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GWACHEON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GWANGMYEONG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GWANGJU;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GURI;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GUNPO;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_GIMPO;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_NAMYANGJU;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_DONGDUCHEON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_BUCHEON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_SEONGNAM;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_SUWON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_SIHEUNG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_ANSAN;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_ANSEONG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_ANYANG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_YANGJU;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_YANGPYEONG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_YEOJU;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_YEONCHEON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_OSAN;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_YONGIN;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_UIWANG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_UIJEONGBU;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_ICHEON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_PAJU;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_PYEONGTAEK;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_POCHEON;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_HANAM;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GYEONGGI_HWASEONG;
    district.depth = 3;
    district.parent = gyeonggi;
    await this.repository.manager.save(district);

    const gangwon = new Career();
    gangwon.slug = CareerEnum.GANGWON;
    gangwon.depth = 2;
    gangwon.parent = korea;
    await this.repository.manager.save(gangwon);

    district = new Career();
    district.slug = CareerEnum.GANGWON_CHEORWON;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_HWACHEON;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_YANGGU;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_GOSEONG;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_SOKCHO;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_INJE;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_YANGYANG;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_CHUNCHEON;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_HONGCHEON;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_GANGNEUNG;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_DONGHAE;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_SAMCHEOK;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_TAEBAEK;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_JEONGSEON;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_PYEONGCHANG;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_HOENGSEONG;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_WONJU;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.GANGWON_YEONGWOL;
    district.depth = 3;
    district.parent = gangwon;
    await this.repository.manager.save(district);

    const northenJeolla = new Career();
    northenJeolla.slug = CareerEnum.NORTHERN_JEOLLA;
    northenJeolla.depth = 2;
    northenJeolla.parent = korea;
    await this.repository.manager.save(northenJeolla);

    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_GUNSAN;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_IKSAN;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_WANJU;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_JINAN;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_MUJU;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_GIMJE;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_JEONJU;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_JANGSU;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_IMSIL;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_BUAN;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_JEONGEUP;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_GOCHANG;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_SUNCHANG;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_JEOLLA_NAMWON;
    district.depth = 3;
    district.parent = northenJeolla;
    await this.repository.manager.save(district);

    const southenJeolla = new Career();
    southenJeolla.slug = CareerEnum.SOUTHERN_JEOLLA;
    southenJeolla.depth = 2;
    southenJeolla.parent = korea;
    await this.repository.manager.save(southenJeolla);

    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_MOKPO;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_YEOSU;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_SUNCHEON;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_NAJU;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_GWANGYANG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_DAMYANG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_GOKSEONG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_GURYE;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_GOHEUNG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_BOSEONG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_HWASUN;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_JANGHEUNG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_GANGJIN;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_HAENAM;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_YEONGAM;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_MUAN;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_HAMPYEONG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_YEONGGWANG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_JANGSEONG;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_WANDO;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_JINDO;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_JEOLLA_SINAN;
    district.depth = 3;
    district.parent = southenJeolla;
    await this.repository.manager.save(district);

    const norhernGyeongsang = new Career();
    norhernGyeongsang.slug = CareerEnum.NORTHERN_GYEONGSANG;
    norhernGyeongsang.depth = 2;
    norhernGyeongsang.parent = korea;
    await this.repository.manager.save(norhernGyeongsang);

    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_POHANG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_GYEONGJU;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_GIMCHEON;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_ANDONG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_GUMI;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_YEONGJU;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_YEONGCHEON;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_SANGJU;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_MUNGYEONG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_GYEONGSAN;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_GUNWI;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_UISEONG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_CHEONGSONG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_YEONGYANG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_YEONGDEOK;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_CHEONGDO;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_GORYEONG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_SEONGJU;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_CHILGOK;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_YECHEON;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_BONGHWA;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_ULJIN;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_GYEONGSANG_ULLEUNG;
    district.depth = 3;
    district.parent = norhernGyeongsang;
    await this.repository.manager.save(district);

    const southernGyeongsang = new Career();
    southernGyeongsang.slug = CareerEnum.SOUTHERN_GYEONGSANG;
    southernGyeongsang.depth = 2;
    southernGyeongsang.parent = korea;
    await this.repository.manager.save(southernGyeongsang);

    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_GEOCHANG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_HAPCHEON;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_CHANGNYEONG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_MIRYANG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_YANGSAN;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_GIMHAE;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_CHANGWON;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_HAMAN;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_UIRYEONG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_SANCHEONG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_HAMYANG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_HADONG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_JINJU;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_SACHEON;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_GOSEONG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_TONGYEONG;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_GEOJE;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_GYEONGSANG_NAMHAE;
    district.depth = 3;
    district.parent = southernGyeongsang;
    await this.repository.manager.save(district);

    const norhernChungcheong = new Career();
    norhernChungcheong.slug = CareerEnum.NORTHERN_CHUNGCHEONG;
    norhernChungcheong.depth = 2;
    norhernChungcheong.parent = korea;
    await this.repository.manager.save(norhernChungcheong);

    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_DANYANG;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_JECHEON;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_CHUNGJU;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_EUMSEONG;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_JINCHEON;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_JEUNGPYEONG;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_GOESAN;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_CHEONGJU;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_BOEUN;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_OKCHEON;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.NORTHERN_CHUNGCHEONG_YEONGDONG;
    district.depth = 3;
    district.parent = norhernChungcheong;
    await this.repository.manager.save(district);

    const southernChungcheong = new Career();
    southernChungcheong.slug = CareerEnum.SOUTHERN_CHUNGCHEONG;
    southernChungcheong.depth = 2;
    southernChungcheong.parent = korea;
    await this.repository.manager.save(southernChungcheong);

    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_DANGJIN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_SEOSAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_TAEAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_HONGSEONG;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_CHEONGYANG;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_BORYEONG;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_SEOCHEON;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_ASAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_CHEONAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_YESAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_GONGJU;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_GYERYONG;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_GEUMSAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_NONSAN;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.SOUTHERN_CHUNGCHEONG_BUYEO;
    district.depth = 3;
    district.parent = southernChungcheong;
    await this.repository.manager.save(district);

    const jeju = new Career();
    jeju.slug = CareerEnum.JEJU;
    jeju.depth = 2;
    jeju.parent = korea;
    await this.repository.manager.save(jeju);
    district = new Career();
    district.slug = CareerEnum.JEJU_JEJU;
    district.depth = 3;
    district.parent = root;
    await this.repository.manager.save(district);
    district = new Career();
    district.slug = CareerEnum.JEJU_SEOGWIPO;
    district.depth = 3;
    district.parent = root;
    await this.repository.manager.save(district);

    const japan = new Career();
    japan.slug = 'japan';
    japan.depth = 1;
    japan.parent = root;
    await this.repository.manager.save(japan);
    const taiwan = new Career();
    taiwan.slug = 'taiwan';
    taiwan.depth = 1;
    taiwan.parent = root;
    await this.repository.manager.save(taiwan);
    const philippines = new Career();
    philippines.slug = 'philippines';
    philippines.depth = 1;
    philippines.parent = root;
    await this.repository.manager.save(philippines);
    const malaysia = new Career();
    malaysia.slug = 'malaysia';
    malaysia.depth = 1;
    malaysia.parent = root;
    await this.repository.manager.save(malaysia);
    const singapore = new Career();
    singapore.slug = 'singapore';
    singapore.depth = 1;
    singapore.parent = root;
    await this.repository.manager.save(singapore);
    const thailand = new Career();
    thailand.slug = 'thailand';
    thailand.depth = 1;
    thailand.parent = root;
    await this.repository.manager.save(thailand);
    const vietnam = new Career();
    vietnam.slug = 'vietnam';
    vietnam.depth = 1;
    vietnam.parent = root;
    await this.repository.manager.save(vietnam);
    const indonesia = new Career();
    indonesia.slug = 'indonesia';
    indonesia.depth = 1;
    indonesia.parent = root;
    await this.repository.manager.save(indonesia);
    const hongkong = new Career();
    hongkong.slug = 'hongkong';
    hongkong.depth = 1;
    hongkong.parent = root;
    await this.repository.manager.save(hongkong);
    const china = new Career();
    china.slug = 'china';
    china.depth = 1;
    china.parent = root;
    await this.repository.manager.save(china);
    const guam = new Career();
    guam.slug = 'guam';
    guam.depth = 1;
    guam.parent = root;
    await this.repository.manager.save(guam);
    const canada = new Career();
    canada.slug = 'canada';
    canada.depth = 1;
    canada.parent = root;
    await this.repository.manager.save(canada);
    const america = new Career();
    america.slug = 'america';
    america.depth = 1;
    america.parent = root;
    await this.repository.manager.save(america);
    const australia = new Career();
    australia.slug = 'australia';
    australia.depth = 1;
    australia.parent = root;
    await this.repository.manager.save(australia);
    const newZealand = new Career();
    newZealand.slug = 'newZealand';
    newZealand.depth = 1;
    newZealand.parent = root;
    await this.repository.manager.save(newZealand);
    const england = new Career();
    england.slug = 'england';
    england.depth = 1;
    england.parent = root;
    await this.repository.manager.save(england);
    const france = new Career();
    france.slug = 'france';
    france.depth = 1;
    france.parent = root;
    await this.repository.manager.save(france);
    const germany = new Career();
    germany.slug = 'germany';
    germany.depth = 1;
    germany.parent = root;
    await this.repository.manager.save(germany);
    const italy = new Career();
    italy.slug = 'italy';
    italy.depth = 1;
    italy.parent = root;
    await this.repository.manager.save(italy);
    const spain = new Career();
    spain.slug = 'spain';
    spain.depth = 1;
    spain.parent = root;
    await this.repository.manager.save(spain);
    const other = new Career();
    other.slug = 'other';
    other.depth = 1;
    other.parent = root;
    await this.repository.manager.save(other);
  }
}
