export enum ArtworkCategory {
  ORIGINAL = 'ORIGINAL',
  LIMITED_PRINT = 'LIMITED_EDITION',
  OPEN_PRINT = 'OPEN_EDITION',
  SCULPTURE = 'SCULPTURE',
  DRAWING = 'DRAWING',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  OTHER = 'OTHER',
}
