export enum Career {
  STUDENT = 'student',
  ACCOUNTING = 'accounting',
  HR = 'hr',
  LEGAL = 'legal',
  STRATEGY = 'strategy',
  DESIGN = 'design',
  MARKETING = 'marketing',
  HARDWARE = 'hardware',
  SOFTWARE = 'software',
  EDUCATION = 'education',
  BIO = 'bio',
  FINANCE = 'finance',
  COMMERCE = 'commerce',
  MEDIA = 'media',
  ART = 'art',
  FOOD = 'food',
  BEAUTY = 'beauty',
  CONSTRUCTION = 'construction',
  GOVERNMENT = 'government',
  ANIMAL = 'animal',
  WELFARE = 'welfare',
  OTHER = 'other',
}
