export enum Career {
  // STUDENT
  SCHOOL_OF_MEDICINE = 'SCHOOL_OF_MEDICINE',
  SCHOOL_OF_PHARMACY = 'SCHOOL_OF_PHARMACY',
  SCHOOL_OF_NURSING = 'SCHOOL_OF_NURSING',
  SCHOOL_OF_VETERINARY_MEDICINE = 'SCHOOL_OF_VETERINARY_MEDICINE',
  SCHOOL_OF_LAW = 'SCHOOL_OF_LAW',
  SCHOOL_OF_ENGINEERING = 'SCHOOL_OF_ENGINEERING',
  SCHOOL_OF_SCIENCE = 'SCHOOL_OF_SCIENCE',
  SCHOOL_OF_BUSINESS = 'SCHOOL_OF_BUSINESS',
  SCHOOL_OF_LANGUAGE_AND_LITERATURE = 'SCHOOL_OF_LANGUAGE_AND_LITERATURE',
  SCHOOL_OF_EDUCATION = 'SCHOOL_OF_EDUCATION',
  SCHOOL_OF_MUSIC = 'SCHOOL_OF_MUSIC',
  SCHOOL_OF_ARTS = 'SCHOOL_OF_ARTS',
  SCHOOL_OF_SPORTS = 'SCHOOL_OF_SPORTS',
  MILITARY_ACADEMY = 'MILITARY_ACADEMY',
  SCHOOL_OF_OTHER_CATEGORIES = 'SCHOOL_OF_OTHER_CATEGORIES',

  // ENTREPRENEUR
  STARTUP = 'STARTUP',
  VENTURE_CAPITAL = 'VENTURE_CAPITAL',
  REAL_ESTATE_INVESTMENT = 'REAL_ESTATE_INVESTMENT',
  FRANCHISE = 'FRANCHISE',
  SMALL_BUSINESS = 'SMALL_BUSINESS',
  FREELANCER = 'FREELANCER',
  OTHER_ENTREPRENEUR = 'OTHER_ENTREPRENEUR',

  // MEDICAL
  DOCTOR = 'DOCTOR',
  ORIENTAL_DOCTOR = 'ORIENTAL_DOCTOR',
  PHARMACIST = 'PHARMACIST',
  ORIENTAL_PHARMACIST = 'ORIENTAL_PHARMACIST',
  VET = 'VET',
  NURSE = 'NURSE',
  OTHER_MEDICAL = 'OTHER_MEDICAL',

  // LEGAL
  JUDGE = 'JUDGE',
  PROSECUTOR = 'PROSECUTOR',
  LAWYER = 'LAWYER',
  OTHER_LEGAL = 'OTHER_LEGAL',

  // HIGH_PAYING_PROFESSION
  PUBLIC_APPRAISER = 'PUBLIC_APPRAISER',
  ARCHITECT = 'ARCHITECT',
  MANAGEMENT_CONSULTANT = 'MANAGEMENT_CONSULTANT',
  FUND_MANAGER = 'FUND_MANAGER',
  LABOR_CONSULTANT = 'LABOR_CONSULTANT',
  PUBLIC_ACCOUNTANT = 'PUBLIC_ACCOUNTANT',
  CUSTOMS_AGENT = 'CUSTOMS_AGENT',
  JUDICIAL_SCRIVENER = 'JUDICIAL_SCRIVENER',
  PATENT_ATTORNEY = 'PATENT_ATTORNEY',
  ACTUARY = 'ACTUARY',
  TAX_ACCOUNTANT = 'TAX_ACCOUNTANT',
  CLAIM_ADJUSTER = 'CLAIM_ADJUSTER',
  FINANCIAL_PLANNER = 'FINANCIAL_PLANNER',
  PILOT = 'PILOT',
  FLIGHT_ATTENDANT = 'FLIGHT_ATTENDANT',
  FLIGHT_ENGINEER = 'FLIGHT_ENGINEER',
  AIR_TRAFFIC_CONTROLLER = 'AIR_TRAFFIC_CONTROLLER',
  SURVEYOR = 'SURVEYOR',
  PUBLIC_ATTORNEY = 'PUBLIC_ATTORNEY',
  OTHER_HIGH_PAYING_PROFESSION = 'OTHER_HIGH_PAYING_PROFESSION',

  // FINANCIAL
  BANK = 'BANK',
  SECURITIES = 'SECURITIES',
  INSURANCE = 'INSURANCE',
  ACCOUNTING = 'ACCOUNTING',
  CRYPTOCURRENCY = 'CRYPTOCURRENCY',
  OTHER_FINANCIAL = 'OTHER_FINANCIAL',

  // RESEARCH
  IT_RESEARCHER = 'IT_RESEARCHER',
  SEMICONDUCTOR_RESEARCHER = 'SEMICONDUCTOR_RESEARCHER',
  SCIENCE_RESEARCHER = 'SCIENCE_RESEARCHER',
  CHEMICAL_RESEARCHER = 'CHEMICAL_RESEARCHER',
  MECHANICAL_RESEARCHER = 'MECHANICAL_RESEARCHER',
  BIO_RESEARCHER = 'BIO_RESEARCHER',
  OTHER_RESEARCHER = 'OTHER_RESEARCHER',

  // ENGINEER
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  HARDWARE_ENGINEER = 'HARDWARE_ENGINEER',
  ARCHITECTUAL_ENGINEER = 'ARCHITECTUAL_ENGINEER',
  ELECTRICAL_ENGINEER = 'ELECTRICAL_ENGINEER',
  MARINE_ENGINEER = 'MARINE_ENGINEER',
  MECHANICAL_ENGINEER = 'MECHANICAL_ENGINEER',
  OTHER_ENGINEER = 'OTHER_ENGINEER',

  // DESIGN
  GRAPHIC_DESIGNER = 'GRAPHIC_DESIGNER',
  UI_UX_DESIGNER = 'UI_UX_DESIGNER',
  FASHION_DESIGNER = 'FASHION_DESIGNER',
  INTERIOR_DESIGNER = 'INTERIOR_DESIGNER',
  PRODUCT_DESIGNER = 'PRODUCT_DESIGNER',
  OTHER_DESIGNER = 'OTHER_DESIGNER',

  // TEACHING
  KINDERGARTEN_TEACHER = 'KINDERGARTEN_TEACHER',
  SCHOOL_TEACHER = 'SCHOOL_TEACHER',
  PROFESSOR = 'PROFESSOR',
  ACADEMY_INSTRUCTOR = 'ACADEMY_INSTRUCTOR',
  TUTOR = 'TUTOR',
  OTHER_TEACHING = 'OTHER_TEACHING',

  // MEDIA
  JOURNALIST = 'JOURNALIST',
  JOURNAL_EDITOR = 'JOURNAL_EDITOR',
  BROADCASTING_WRITER = 'BROADCASTING_WRITER',
  ACTOR = 'ACTOR',
  COMEDIAN = 'COMEDIAN',
  VOICE_ACTOR = 'VOICE_ACTOR',
  MODEL = 'MODEL',
  ANNOUNCER = 'ANNOUNCER',
  OTHER_MEDIA = 'OTHER_MEDIA',

  // ENTERTAINMENT
  ENTERTAINMENT_MANAGER = 'ENTERTAINMENT_MANAGER',
  E_SPORTS_PLAYER = 'E_SPORTS_PLAYER',
  STREAMER = 'STREAMER',
  INFLUENCER = 'INFLUENCER',
  OTHER_ENTERTAINMENT = 'OTHER_ENTERTAINMENT',

  // SPORTS
  COACH = 'COACH',
  SPORTS_INSTRUCTOR = 'SPORTS_INSTRUCTOR',
  ATHLETE = 'ATHLETE',
  FITNESS_TRAINER = 'FITNESS_TRAINER',
  OTHER_SPORTS = 'OTHER_SPORTS',

  // ARTS
  VOCALIST = 'VOCALIST',
  MUSICIAN = 'MUSICIAN',
  DANCER = 'DANCER',
  PAINTER = 'PAINTER',
  SCULPTOR = 'SCULPTOR',
  OTHER_ARTS = 'OTHER_ARTS',

  // SERVICE
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  LANGUAGE_SERVICE = 'LANGUAGE_SERVICE',
  BEAUTY_SERVICE = 'BEAUTY_SERVICE',
  ENVIRONMENTAL_SERVICES = 'ENVIRONMENTAL_SERVICES',
  PET_SERVICE = 'PET_SERVICE',
  SECURITY_SERVICE = 'SECURITY_SERVICE',
  OTHER_SERVICE = 'OTHER_SERVICE',

  // GOVERNMENT
  GOVERNMENT_OFFICIAL = 'GOVERNMENT_OFFICIAL',
  FOREIGN_SERVICE = 'FOREIGN_SERVICE',
  POLICE_FORCE = 'POLICE_FORCE',
  FIRE_SERVICE = 'FIRE_SERVICE',
  MILITARY_SERVICE = 'MILITARY_SERVICE',
  SOLDIER = 'SOLDIER',
  OTHER_GOVERNMENT = 'OTHER_GOVERNMENT',

  // OTHER
  SALES = 'SALES',
  RETAIL = 'RETAIL',
  FARMING = 'FARMING',
  FISHERY = 'FISHERY',
  BETWEEN_JOBS = 'BETWEEN_JOBS',
  NONE = 'NONE',
}
