export enum CategoryEnum {
  // LEISURE = 'leisure'
  DINING = 'dining', // 식사
  CAFE = 'cafe', // 커피,카페
  ALCOHOL = 'alcohol', // 술
  MOVIE = 'movie', // 영화
  NETFLIX = 'netflix', // OTT
  WEBTOON = 'webtoon', // WEBTOON
  THEATER = 'theater', // 연극
  CONCERT = 'concert', // 콘서트,KStar
  STADIUM = 'stadium', // 스포츠관람
  INDIE = 'indie', // 인디밴드,버스킹
  EXHIBITION = 'exhibition', // 공원
  PARK = 'park', // 공원
  THEMEPARK = 'themepark', // 테마파크
  TRAVEL = 'travel', // 트래블
  SAUNA = 'sauna', // 찜질방,사우나
  OTHER_LEISURE = 'otherLeisure',
  // HOBBY = 'hobby'
  GUITAR = 'guitar', // 기타
  PIANO = 'piano', // 피아노
  KARAOKE = 'karaoke', // 노래방
  KPOP_DANCE = 'kpopDance', // KPOP댄스
  BALLROOM_DANCE = 'ballroomDance', // 볼룸댄스
  DRAWING = 'drawing', // 일러스트
  PAINTING = 'painting', // 원화그림
  POTTERY = 'pottery', // 도자기
  CRAFTING = 'crafting', // 공예
  BOARD_GAME = 'boardGame', // 보드게임
  PC_GAME = 'pcGame', // PC게임
  CONSOLE_GAME = 'consoleGame', // 비디오게임
  FISHING = 'fishing', // 낚시
  CAMPING = 'camping', // 캠핑
  DRIVING = 'driving', // 떼빙
  STEREO = 'stereo', // 스테레오
  PLAMODEL = 'plamodel', // 프라모델
  COOKING = 'cooking', // 요리
  SHOPPING = 'shopping', // 쇼핑
  PHOTO_SHOOTING = 'photoShooting', // 사진출사
  PLANTING = 'planting', // 반려식물
  PET = 'pet', // 반려동물
  OTHER_HOBBY = 'otherHobby',
  // SPORTS = 'sports'
  BADMINTON = 'badminton', // 배드민턴
  BASEBALL = 'baseball', // 야구
  BASKETBALL = 'basketball', // 농구
  VOLLEYBALL = 'volleyball', // 배구
  FOOTBALL = 'football', // 축구
  FUTSAL = 'futsal', // 풋살
  DODGEBALL = 'dodgeball', // 피구
  RACQUETBALL = 'racquetball', // 라켓볼
  TENNIS = 'tennis', // 테니스
  PINGPONG = 'pingpong', // 탁구
  BOWLING = 'bowling', // 볼링
  POOL = 'pool', // 당구
  GOLF = 'golf', // 골프
  MOUNTAIN = 'mountain', // 등산
  CLIMBING = 'climbing', // 클라이밍
  BIKE = 'bike', // 바이크
  MOUNTAIN_BIKE = 'mountainBike', // 마운틴바이크
  ROLLER_SKATING = 'rollerSkating', // 롤러스케이팅
  ICE_SKATING = 'iceSkating', // 아이스스케이팅
  SKI = 'ski', // 스키,스노보드
  SWIMMING = 'swimming', // 수영
  SCUBA_DIVING = 'scubaDiving', // 스쿠버다이빙
  WALKING = 'walking', // 걷기
  RUNNING = 'running', // 달리기
  WORKOUT = 'workout', // 짐
  AEROBIC = 'aerobic', // 에어로빅
  YOGA = 'yoga', // 요가,필라테스
  ARCHERY = 'archery', // 양궁
  HORSEBACK = 'horseback', // 승마
  OTHER_SPORTS = 'otherSports',
  // OTHER = 'other',
  TALK_ONLINE = 'talkOnline', // Online
  ONE_DAY_CLASS = 'oneDayClass', // 공부
  VOLUNTARY_ACTIVITY = 'voluntaryActivity',
  LANGUAGE = 'language', // 언어교환
  READING = 'reading', // 독서
  CODING = 'coding', // 코딩
  STUDY = 'study', // 공부
  YOUTUBE = 'youtube', // 유튜버
  SECURITIES = 'securities', // 주식
  CRYPTO = 'crypto', // 코인
  ENTREPRENEURSHIP = 'entrepreneurship', // 사업,창업
  MENTORSHIP = 'mentorship', // 멘터
  ALL_OTHER = 'allOther',
}
