export enum Keyword {
  ALCOHOL_NONE = 'alcoholNone',
  ALCOHOL_SOJU = 'alcoholSoju',
  ALCOHOL_BEER = 'alcoholBeer',
  ALCOHOL_WINE = 'alcoholWine',
  ALCOHOL_WHISKY = 'alcoholWhisky',
  ALCOHOL_MAKGEOLLI = 'alcoholMakgeolli',
  ALCOHOL_SAKE = 'alcoholSake',
  TATOO_NONE = 'tatooNone',
  TATOO_HIDDEN = 'tatooHidden',
  TATOO_LIGHT = 'tatooLight',
  TATOO_HEAVY = 'tatooHeavy',
  SMOKNING_NONE = 'smokingNone',
  SMOKNING_LIGHT = 'smokingLight',
  SMOKNING_HEAVY = 'smokingHeavy',
  RELIGION_NONE = 'religionNone',
  RELIGION_BUDDHISM = 'religionBuddhism',
  RELIGION_CATHOLICISM = 'religionCathlicism',
  RELIGION_PROTESTANTISM = 'religionProtestantism',
  RELIGION_HINDUISM = 'religionHinduism',
  RELIGION_ISLAM = 'religionIslam',
  MUSIC_NONE = 'musicNone',
  MUSIC_BALLARD = 'musicBallard',
  MUSIC_HIPHOP = 'musicHiphop',
  MUSIC_ROCK = 'musicRock',
  MUSIC_POP = 'musicPop',
  MUSIC_CLASSIC = 'musicClassic',
}
