export enum PaymentMethod {
  card = 'card',
  trans = 'trans',
  vbank = 'vbank',
  phone = 'phone',
  samsung = 'samsung',
  kakaopay = 'kakaopay',
  naverpay = 'naverpay',
  payco = 'payco',
  lpay = 'lpay',
  ssgpay = 'ssgpay',
  tosspay = 'tosspay',
  cultureland = 'cultureland',
  smartculture = 'smartculture',
  happymoney = 'happymoney',
  chai = 'chai',
}
