export enum PaymentMethod {
  card = 'card',
  trans = 'trans',
  vbank = 'vbank',
  phone = 'phone',
  samsung = 'samsung',
  kpay = 'kpay',
  kakaopay = 'kakaopay',
  payco = 'payco',
  lpay = 'lpay',
  ssgpay = 'ssgpay',
  tosspay = 'tosspay',
  cultureland = 'cultureland',
  smartculture = 'smartculture',
  happymoney = 'happymoney',
  booknlife = 'booknlife',
  point = 'point',
  wechat = 'wechat',
  alipay = 'alipay',
  unionpay = 'unionpay',
  tenpay = 'tenpay',
}
