export enum Subject {
  ABSTRACT = 'ABSTRACT',
  ANIMALS = 'ANIMALS',
  CITYSCAPES = 'CITYSCAPES',
  FLOWERS = 'FLOWERS',
  LANDSCAPE = 'LANDSCAPE',
  NATURE = 'NATURE',
  PEOPLE = 'PEOPLE',
  STILL_LIFE = 'STILL_LIFE',
  OTHER = 'OTHER',
}
